# Generated by Django 5.0 on 2024-08-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField(max_length=40)),
                ('duracao', models.CharField(max_length=30)),
                ('link_video_treino', models.CharField(default='RpC7sv8_LIg', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(default='Treino', max_length=30)),
                ('caminho_treino_url', models.CharField(default='nome_treino', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('nome', models.CharField(max_length=30)),
                ('repeticoes', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='ballers085.treinos')),
            ],
        ),
    ]
